#!/usr/bin/env python 

import hdf5plugin
import h5py
import os
from pathlib import Path
import argparse
import matplotlib.pyplot as plt
plt.ion()

#puts us in interactive more
os.environ['PYTHONINSPECT'] = 'TRUE'

if __name__ == "__main__":
    #TODO! move to hdf5file class inside hdf5maker

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "fname", 
        help="File name to open", 
        type=Path, 
    )
    args = parser.parse_args()

    f = h5py.File(args.fname, 'r')
    ds = [s for s in f['entry/data'].values()]