python:
    - 3.12
    - 3.13
    - 3.14

c_compiler:
  - gcc                        # [linux]

c_stdlib:
  - sysroot                    # [linux]

cxx_compiler:
  - gxx                        # [linux]

c_stdlib_version:              # [linux]
  - 2.17                       # [linux]