
package:
  name: hdf5maker
  version: "{{ load_setup_py_data().version }}"

build:
  number: 0
  script: 
    - {{ PYTHON }} -m pip install . -vv  # [not win]

source:
  path: ../

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}



  host:
    - python 
    - numpy>=2.1
    - pip
    - setuptools

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - h5py
    - hdf5plugin
    - matplotlib

test:
  imports:
    - hdf5maker

about:
  home: https://github.com/slsdetectorgroup/hdf5maker
  license: MIT
  summary: Raw to hdf5 converter for PSI Eiger detector
