python:
    - 3.8
    - 3.8
    - 3.8
    - 3.9 
    - 3.9 
    - 3.9 
    - 3.10
    - 3.10
    
numpy: 
    - 1.20
    - 1.21
    - 1.22
    - 1.20
    - 1.21
    - 1.22
    - 1.21
    - 1.22

zip_keys:
    - python
    - numpy

pin_run_as_build:
  numpy: x.x
  python: x.x
