python:
    - 3.9 
    - 3.9 
    - 3.9 
    - 3.10
    - 3.10
    - 3.10
    - 3.11
    - 3.11

    
numpy: 
    - 1.21
    - 1.22
    - 1.23
    - 1.21
    - 1.22
    - 1.23
    - 1.23
    - 1.24

zip_keys:
    - python
    - numpy

pin_run_as_build:
  numpy: x.x
  python: x.x
