
package:
  name: hdf5maker
  version: "{{ load_setup_py_data().version }}"
  script: build.sh

source:
  path: ..

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy
    - h5py
    - hdf5plugin

test:
  imports:
    - hdf5maker

about:
  home: https://github.com/slsdetectorgroup/hdf-maker-experimental
  license: GPL3
  license_family: GPL
  summary: Raw to hdf5 converter for PSI Eiger detector