
package:
  name: hdf5maker
  version: "{{ load_setup_py_data().version }}"
  script: build.sh

source:
  path: ..

requirements:
  build:
    - python {{python}}
    - numpy  {{ numpy }}

  host:
    - python {{python}}
    - numpy  {{ numpy }}

  run:
    - python {{python}}
    - numpy {{ numpy }}
    - h5py
    - hdf5plugin
    - matplotlib

test:
  imports:
    - hdf5maker

about:
  home: https://github.com/slsdetectorgroup/hdf5maker
  license: GPL3
  license_family: GPL
  summary: Raw to hdf5 converter for PSI Eiger detector
