name: Python Package Using Anaconda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        activate-environment: test
        environment-file: .github/workflows/environment.yml
        python-version: 3.9
        auto-activate-base: false
    - shell: bash -l {0}
      run: |
        conda info
        conda list
    - name: Build conda pkg
      shell: bash -l {0}
      run: |
          conda build .
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: conda-pkgs
        path: /usr/share/miniconda/envs/test/conda-bld/linux-64/*.tar.bz2

