name: Build pkgs and deploy if on main

on:
  release:
      types:
        - published

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, ] # macos-12, windows-2019]
        python-version: ["3.12",]

    runs-on: ${{ matrix.platform }}

    # The setup-miniconda action needs this to activate miniconda
    defaults:
      run:
        shell: "bash -l {0}"

    steps:
      - uses: actions/checkout@v4

      - name: Get conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: etc/dev-env.yml
          miniforge-version: latest
          channels: conda-forge
          conda-remove-defaults: "true"

      - name: Enable upload
        run: conda config --set anaconda_upload yes

      - name: Build
        env:
          CONDA_TOKEN: ${{ secrets.CONDA_TOKEN }}
        run: conda build conda-recipe --user slsdetectorgroup --token ${CONDA_TOKEN}